name: conda_test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - streamlit
    - numpy
    - pandas
    - wordcloud
    - spotipy
    - scipy
    - altair
    - isort
  - python=3.10
  - plotly==5.7.0
