name: spotify-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - streamlit
    - numpy
    - pandas
    - wordcloud
    - spotipy
    - scipy
    - altair
    - isort
    - pre-commit
  - python=3.9
  - plotly==5.7.0
