name: spotify-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - streamlit
    - numpy
    - pandas
    - wordcloud
    - spotipy
    - altair
    - isort
    - pre-commit
  - python=3.10
  - plotly==5.7.0
